In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Coleta de dados

In [215]:
df = pd.read_csv('../datasets/dados_clientes.csv')
df.head()

,id_cliente,nome,idade,genero,renda_anual,categoria_produto,valor_compra,data_compra,regiao
0,1006,Gabriela Rocha,40.0,Masculino,750000.000000,Eletrônicos,1084.904523,2024-01-15,Centro-Oeste
1,1019,Isabela Martins,42.0,Outro,174931.504986,Casa,984.100186,2024-04-05,Norte
2,1014,Gabriela Rocha,33.0,Outro,180660.619728,Moda,2017.981504,2024/03/10,Norte
3,1010,Sabrina Torres,58.0,Feminino,95133.980567,Esporte,4981.455814,2024/03/10,Nordeste
4,1007,Daniel Costa,42.0,Outro,96879.401953,Beleza,2052.315229,2024-06-22,Centro-Oeste

### Observação de dados

In [216]:
df_fill = df.copy()
df_fill.isna().sum()
df_fill.isna().mean() * 100
df_fill['renda_anual'] = df['renda_anual'].fillna(df['renda_anual'].median())
df_fill['idade'] = df['idade'].fillna(df['idade'].median())
df_fill['valor_compra'] = df['valor_compra'].fillna(df['valor_compra'].median())
df_fill['data_compra'] = df['data_compra'].ffill()

df_fill.describe()

        id_cliente      idade    renda_anual  valor_compra
count    30.000000  30.000000      30.000000     30.000000
mean   1009.733333  38.966667  157434.674484   3832.995692
std       5.918605  12.124308  139925.259729   3978.118077
min    1000.000000  18.000000   39809.346415    984.100186
25%    1005.250000  31.000000   77583.677680   2017.981504
50%    1010.000000  40.000000  165339.227930   2612.869185
75%    1014.000000  42.000000  173009.293206   4200.962989
max    1019.000000  62.000000  750000.000000  20000.000000

In [220]:
# Avalidando dados duplicados
df['id_cliente'].duplicated().sum()
df_duplicados = df.copy()
df_duplicados = df_duplicados.drop_duplicates(subset='id_cliente', keep='last')
df_duplicados['id_cliente'].duplicated().sum()

np.int64(0)